version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sample
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dev:1234@postgres:5432/sample?schema=public
    ports:
      - '3000:3000'

volumes:
  postgres_data:
