version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'

  nest-app:
    build: .
    container_name: nest-container
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
    depends_on:
      - db
    ports:
      - '3000:3000'
